# environment.yml

name: agentive-inventory
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - fastapi
  - uvicorn
  - pydantic
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - requests
  - streamlit
  - altair
  - pyyaml
  - pytest
  - mypy
  - ruff
  - pip:
      - google-genai>=0.3
      - prophet>=1.1.5
