# render.yaml

services:
  # --- FastAPI backend (no disk; symlink to repo-root data/configs) ---------
  - type: web
    name: agentive-api
    runtime: python
    rootDir: backend
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      # expose repo-root data/ & configs/ to code expecting backend-local paths
      ln -sfn ../data data || true
      ln -sfn ../configs configs || true
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: LOG_LEVEL
        value: info
      # Lock CORS to your UI after first deploy if desired:
      # - key: CORS_ORIGINS
      #   value: https://agentive-ui.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: API_TOKEN
        sync: false
      - key: RATE_LIMIT_PER_MIN
        value: "60"

  # --- Streamlit UI ---------------------------------------------------------
  - type: web
    name: agentive-ui
    runtime: python
    rootDir: frontend
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    healthCheckPath: /
    envVars:
      - key: API_URL
        value: https://agentive-api.onrender.com/api/v1
      - key: API_TOKEN
        sync: false

  # # --- (Optional) n8n on free tier (no disk; state resets on redeploy) ------
  # - type: web
  #   name: agentive-n8n
  #   runtime: docker
  #   image:
  #     url: n8nio/n8n:latest
  #   healthCheckPath: /
  #   dockerCommand: sh -lc 'export N8N_PORT=$PORT; n8n start'
  #   envVars:
  #     - key: N8N_HOST
  #       value: agentive-n8n.onrender.com
  #     - key: N8N_PORT
  #       value: "10000"
  #     - key: WEBHOOK_URL
  #       value: https://agentive-n8n.onrender.com/
  #     - key: API_URL
  #       value: https://agentive-api.onrender.com/api/v1
  #     - key: N8N_BASIC_AUTH_ACTIVE
  #       value: "true"
  #     - key: N8N_BASIC_AUTH_USER
  #       sync: false
  #     - key: N8N_BASIC_AUTH_PASSWORD
  #       sync: false
  #     - key: N8N_ENCRYPTION_KEY
  #       sync: false