version: "3.8"

services:
  backend:
    build:
      context: ../backend
    container_name: agentive-backend
    volumes:
      - ../data:/app/data:ro
      - ../configs:/app/configs:ro
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    container_name: agentive-frontend
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/api/v1
    ports:
      - "8501:8501"
    restart: unless-stopped