# configs\thresholds.yaml

# Guardrails and threshold configuration.
#
# These values determine when procurement recommendations should be auto‑approved
# versus flagged for human intervention.  Tune them to suit your business.

auto_approval_limit: 1000.0  # If order spend (qty * unit_cost) <= this, auto-approve
min_service_level: 0.90      # If forecast confidence below this, require approval
gmroi_min: 0.05              # Minimum acceptable GMROI delta (dimensionless proxy)
