# .github\workflows\ci.yml

name: ci
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r frontend/requirements.txt
          pip install pytest pytest-cov mypy ruff
      - name: Ruff
        run: ruff check .
      - name: Mypy (backend)
        run: mypy backend
      - name: Pytest
        run: pytest -q --maxfail=1 --disable-warnings --cov=backend --cov-report=term-missing --junitxml=pytest-report.xml
      - name: Upload JUnit
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-report
          path: pytest-report.xml
