name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt -r frontend/requirements.txt ruff mypy pytest
      - name: Lint
        run: ruff check .
      - name: Type check backend
        run: mypy backend/app
      - name: Run tests
        run: pytest backend